using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace HistoryIn20Events
{
    internal static class EventsDB
    {
        public static List<HistoricalEvent> Events { get; private set; }

        static EventsDB()
        {
            Events = new List<HistoricalEvent>()
            {
                new HistoricalEvent("30", "Crucifixion of Jesus Christ", "Execution and resurrection of Jesus. Birth of Christianity during the Roman era.", "BC (Before Christ) to the Birth of Jesus Christ, transitioning to AD (Anno Domini; Latin for 'in the year of our Lord'). In BC, transition from Greece to Macedonia (Alexander the Great) to Rome."),
                new HistoricalEvent("476", "Fall of the Western Roman Empire", "The fall of the Western Roman Empire marks the beginning of the Middle Ages. The empire was overthrown by Odoacer, a Germanic chieftain, leading to significant cultral and political changes in Europe.", "The fall of the Western Roman Empire is often considered the start of the Middle Ages, around the 4th to 6th centuries, with the migration of Germanic tribes. This period saw the blending of Greco-Roman traditions with Germanic cultures, laying the foundation for modern Western civilization."),
                new HistoricalEvent("622", "Hijira (Muhammad's migration to Medina)", "Muhammad's migration from Mecca to Medina due to persecution. This event marks the beginning of the Islamic calendar."),
                new HistoricalEvent("1096", "First Crusade", "The First Crusade was launched to reclaim the Holy Land, Jerusalem, from Islamic control. It initiated a series of religious and military campaigns that lasted until the 13th century.", "The Crusades, lasting from the 11th to the 13th centuries, were a series of religious wars sanctioned by the Latin Church. The First Crusade was a significant event that set the stage for nearly two centuries of intermittent conflict between Christian and Muslim powers, highlighting of medieval culture and society."),
                new HistoricalEvent("1320", "Dante's 'Divine Comedy'", "Dante Alighieri's 'Divine Comedy' marks the beginning of the Renaissance. It is a cornerstone of Italian literature and a significant cultural and artistic achievement of the Middle Ages."),
                new HistoricalEvent("1453", "Fall of the Byzantine Empire", "The fall of Constantinople to the Ottoman Turks, marking the end of the Byzantine Empire and the Middle Ages."),
                new HistoricalEvent("1492", "Christopher Columbus Discover America", "Columbus's voyage led to the widespread awareness of the American continents and the beginning of European exploration and colonization.", "Columbus's discovery of America marked the beginning of the Age of Exploration (15th to 17th centuries), during which European powers expanded globally. This era saw the establishment of numerous colonies and the eventual decline of indigenous empires like the Inca. Columbus's journey is often considered the starting point of the modern Western world's expansion and influence."),
                new HistoricalEvent("1517", "Martin Luther's 95 Theses", "Martin Luther's act of nailing his 95 Theses to the church door in Wittenberg sparked the Protestant Reformation, challenging the authority of the Catholic Church.", "The Reformation led to significant religious, political, and social changes in Europe. It challenged the Catholic Church's dominance, leading to wars such as the Thirty Years' War. The Reformation also influenced the development of modern democracy and the nation-state, shaping the cultural and intellectual landscape of the 16th to 18th centuries."),
                new HistoricalEvent("1543", "Copernicus' Heliocentric Theory", "Nicolaus Copernicus published his theory that the Earth orbits the Sun, laying the groundwork for modern astronomy and the scientific revolution.", "Copernicus's heliocentric model challenged the geocentric view and inspired future astronomers like Kepler and Galileo. This shift in understanding paved the way for the Scientific Revolution(17th century with Newton's 'Principia'), which emphasized empirical evidence and mathematical principles in understanding the natural world. The idea that 'the language of nature is mathematics' became central to this transformation."),
                new HistoricalEvent("1588", "Defeat of the Spanish Armada", "The English navy's victory over the Spanish Armada marked the decline of Spain's maritime dominance and the rise of England as a global naval power.", "The defeat of the Armada in 1588 was not just a military victory for England but also a turning point in European history. It marked the decline of Spain's influence and the rise of England under Queen Elizabeth I. The battle symbolized the conflict between Catholic Spain and Protestant England, influencing the religious and political balance of power in Europe."),
                new HistoricalEvent("1760", "Start of the Industrial Revolution", "The Industrial Revolution began in Britain, leading to significant technological, economic, and social changes worldwide.", "The Industrial Revolution, spanning from 1760 to 1830, transformed economies from agrarian to industrial. It introduced innovations like the steam engine, leading to mass production and urbanization. This era dramatically improved living standards and productivity, laying the foundations for the modern capitalist economy."),
                new HistoricalEvent("1776", "American Declaration of Independence", "The Thirteen American colonies declared independence from British rule, leading to the formation of the United States.", "The Declaration of Independence in 1776 marked the birth of a new nation based on principles of liberty and democracy. The American Revolution inspired subsequent democratic movements worldwide and established the United States as a model for republican governance and individual rights."),
                new HistoricalEvent("1789", "French Revolution", "The French Revolution overthrew the monarchy, established a republic, and inspired widespread revolutionary movements across Europe.", "The French Revolution began with the storming of the Bastille and led to significant changes in French society, including the abolition of feudal priviledges and the rise of secularism. It introduced concepts of citizenship and inalienable rights, influencing political thought and revolutions globally. The revolution also set the stage for Napoleon's rise to power."),
                new HistoricalEvent("1861", "American Civil War", "A conflict between the Northern states (Union) and Southern states (Confederacy) over slavery and states' rights, leading to the abolition of slavery.", "The American Civil War, fought from 1861 to 1865, was a defining moment in U.S. history. It resolved the issues of secession and slavery, leading to the preservation of the Union and the abolition of slavery through the 13th Amendment. The war's aftermath included Reconstruction and significant social and economic changes."),
                new HistoricalEvent("1871", "Unification of Germany", "The unification of Germany under Prussian leadership, transforming it into a major European power.", "The unification of Germany in 1871 marked the consolidation of various German states into a single nation under the leadership of Otto von Bismarck and Prussia. This event significantly altered the balanced of power in Europe and set the stage for Germany's role in future conflicts, including the World Wars. It also influenced the unification of Italy around the same period."),
                new HistoricalEvent("1876", "Alexander Graham Bell's Telephone Patent", "Alexander Graham Bell was granted a patent for the telephone, revolutionizing communication.", "The invention of the telephone by Alexander Graham Bell in 1876 was a milestone in communication technology. It paved the way for the global telecommunications industry, transforming personal and business communication. This period also saw other significant inventions, such as Edison's light bulb(1879) and Daimler's automobile(1882), which contributed to the technological advancements of the late 19th century."),
                new HistoricalEvent("1914", "Start of World War I", "The First World War began, involving many of the world's great powers and leading to significant geopolitical changes.", "World War I (1914-1918) marked a significant transition from the 19th to the 20th century, often considered the end of the modern era and the beginning of the contemporary era. Prior to the war, Europe experienced a long period of peace. The war's end led to major political changes, including the Russian Revolution and the fall of empires, reshaping the global political landscape."),
                new HistoricalEvent("1917", "Russian Revolution", "The Bolshevik Revolution led to the overthrow of the Romanov dynasty and the establishment of the Soviet Union."), 
                new HistoricalEvent("1939", "Start of World War II", "The second World War began with Germany's invasion of Poland, leading to a global conflict involving most of the world's nations.", "World War II (1939-1945) was triggered by Germany's aggressive expansion under Adolf Hitler. Key events include the invasion of Poland, the Battle of Britain, the German invasion of the Soviet Union, and the attack on Pearl Harbor, which brought the United States into the war. The war ended with the defeat of the Axis powers, leading to the Cold War and significant geopolitical changes."),
                new HistoricalEvent("1962", "Cuban Missile Crisis", "A tense confrontation between the United States and the Soviet Union over the presence of Soviet ballistic missiles in Cuba, bringing the world close to nuclear war.", "The Cuban Missile Crisis of 1962 was the closest the Cold War came to escalating into a full-scale nuclear war. The crisis began when teh U.S. dicovered Soviet missiles in Cuba, leading to a 13-day political and military standoff. It ended with the Soviets agreeing to dismantle the missiles in exchange for the U.S. promising not to invade Cuba and secretly removing missiles from Turkey."),
                new HistoricalEvent("1991", "Fall of the Soviet Union", "The dissolution of the Soviet Union marked the end of the Cold War and the emergence of the United States as the world's sole superpower.", "The fall of the Soviet Union in 1991 was preceded by the decline of communist regimes in Eastern Europe, starting with Poland in 1989 and followed by the reunification of Germany in 1990. The Soviet Union, a federation of various republics, dissolved as member states declared independence. This event marked the end of the Cold War, the collapse of communism in the region, and significant geopolitical shifts, including the rise of the United States as the dominant global power and China's emergence as a major rival."),
            };
        }
    }
}
